export default {
  statuses: [
    {
      created_at: 'Sat Sep 02 21:25:04 +0000 2017',
      id: 904092837704237056,
      id_str: '904092837704237056',
      text:
        'Use the multilib repository to run and build 32-bit apps on 64-bit Arch Linux.',
      truncated: false,
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [],
        urls: [],
      },
      metadata: {
        iso_language_code: 'en',
        result_type: 'recent',
      },
      source:
        '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: null,
      in_reply_to_user_id_str: null,
      in_reply_to_screen_name: null,
      user: {
        id: 900805125362634752,
        id_str: '900805125362634752',
        name: 'John Sanelli',
        screen_name: 'JohnSanelli',
        location: 'New York Cit',
        description: 'M2M Entrepreneur',
        url: null,
        entities: {
          description: {
            urls: [],
          },
        },
        protected: false,
        followers_count: 3,
        friends_count: 10,
        listed_count: 0,
        created_at: 'Thu Aug 24 19:40:52 +0000 2017',
        favourites_count: 6,
        utc_offset: -25200,
        time_zone: 'Pacific Time (US & Canada)',
        geo_enabled: false,
        verified: false,
        statuses_count: 8,
        lang: 'en',
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: 'F5F8FA',
        profile_background_image_url: null,
        profile_background_image_url_https: null,
        profile_background_tile: false,
        profile_image_url:
          'http://pbs.twimg.com/profile_images/900808734649266178/_JueV7sX_normal.jpg',
        profile_image_url_https:
          'https://pbs.twimg.com/profile_images/900808734649266178/_JueV7sX_normal.jpg',
        profile_link_color: '1DA1F2',
        profile_sidebar_border_color: 'C0DEED',
        profile_sidebar_fill_color: 'DDEEF6',
        profile_text_color: '333333',
        profile_use_background_image: true,
        has_extended_profile: false,
        default_profile: true,
        default_profile_image: false,
        following: null,
        follow_request_sent: null,
        notifications: null,
        translator_type: 'none',
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 0,
      favorite_count: 1,
      favorited: false,
      retweeted: false,
      lang: 'en',
    },
    {
      created_at: 'Sun Sep 03 20:05:30 +0000 2017',
      id: 904435202432389120,
      id_str: '904435202432389120',
      text:
        'Con Trump a la cabeza, la comunidad internacional condenó a Corea del Norte https://t.co/hgxrEIQg1T https://t.co/Q4ugDV52Ze',
      truncated: false,
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [],
        urls: [
          {
            url: 'https://t.co/hgxrEIQg1T',
            expanded_url: 'http://bit.ly/2vWJZij',
            display_url: 'bit.ly/2vWJZij',
            indices: [76, 99],
          },
        ],
        media: [
          {
            id: 904435198976249856,
            id_str: '904435198976249856',
            indices: [100, 123],
            media_url: 'http://pbs.twimg.com/media/DI0zBYVW0AAyOmm.jpg',
            media_url_https: 'https://pbs.twimg.com/media/DI0zBYVW0AAyOmm.jpg',
            url: 'https://t.co/Q4ugDV52Ze',
            display_url: 'pic.twitter.com/Q4ugDV52Ze',
            expanded_url:
              'https://twitter.com/Cronistacom/status/904435202432389120/photo/1',
            type: 'photo',
            sizes: {
              medium: {
                w: 630,
                h: 315,
                resize: 'fit',
              },
              small: {
                w: 630,
                h: 315,
                resize: 'fit',
              },
              thumb: {
                w: 150,
                h: 150,
                resize: 'crop',
              },
              large: {
                w: 630,
                h: 315,
                resize: 'fit',
              },
            },
          },
        ],
      },
      extended_entities: {
        media: [
          {
            id: 904435198976249856,
            id_str: '904435198976249856',
            indices: [100, 123],
            media_url: 'http://pbs.twimg.com/media/DI0zBYVW0AAyOmm.jpg',
            media_url_https: 'https://pbs.twimg.com/media/DI0zBYVW0AAyOmm.jpg',
            url: 'https://t.co/Q4ugDV52Ze',
            display_url: 'pic.twitter.com/Q4ugDV52Ze',
            expanded_url:
              'https://twitter.com/Cronistacom/status/904435202432389120/photo/1',
            type: 'photo',
            sizes: {
              medium: {
                w: 630,
                h: 315,
                resize: 'fit',
              },
              small: {
                w: 630,
                h: 315,
                resize: 'fit',
              },
              thumb: {
                w: 150,
                h: 150,
                resize: 'crop',
              },
              large: {
                w: 630,
                h: 315,
                resize: 'fit',
              },
            },
          },
        ],
      },
      source:
        '<a href="https://secure.echoboxapp.com" rel="nofollow">Echobox Social</a>',
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: null,
      in_reply_to_user_id_str: null,
      in_reply_to_screen_name: null,
      user: {
        id: 62806842,
        id_str: '62806842',
        name: 'Cronistacom',
        screen_name: 'Cronistacom',
        location: 'Argentina',
        description: 'Economía en tiempo real',
        url: 'http://t.co/m5rM3TE45a',
        entities: {
          url: {
            urls: [
              {
                url: 'http://t.co/m5rM3TE45a',
                expanded_url: 'http://www.Cronista.com',
                display_url: 'Cronista.com',
                indices: [0, 22],
              },
            ],
          },
          description: {
            urls: [],
          },
        },
        protected: false,
        followers_count: 145481,
        friends_count: 4228,
        listed_count: 2051,
        created_at: 'Tue Aug 04 12:42:29 +0000 2009',
        favourites_count: 262,
        utc_offset: -10800,
        time_zone: 'Buenos Aires',
        geo_enabled: false,
        verified: true,
        statuses_count: 123959,
        lang: 'es',
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: '709397',
        profile_background_image_url:
          'http://pbs.twimg.com/profile_background_images/378800000082947056/91849db20c17d49267de814232abb027.png',
        profile_background_image_url_https:
          'https://pbs.twimg.com/profile_background_images/378800000082947056/91849db20c17d49267de814232abb027.png',
        profile_background_tile: false,
        profile_image_url:
          'http://pbs.twimg.com/profile_images/433312698005078017/f2W4NDGb_normal.png',
        profile_image_url_https:
          'https://pbs.twimg.com/profile_images/433312698005078017/f2W4NDGb_normal.png',
        profile_banner_url:
          'https://pbs.twimg.com/profile_banners/62806842/1472003666',
        profile_link_color: 'FF3300',
        profile_sidebar_border_color: 'FFFFFF',
        profile_sidebar_fill_color: 'FFF3E5',
        profile_text_color: '335273',
        profile_use_background_image: true,
        has_extended_profile: false,
        default_profile: false,
        default_profile_image: false,
        following: null,
        follow_request_sent: null,
        notifications: null,
        translator_type: 'none',
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 1,
      favorite_count: 11,
      favorited: false,
      retweeted: false,
      possibly_sensitive: false,
      possibly_sensitive_appealable: false,
      lang: 'es',
    },
    {
      created_at: 'Sat Sep 02 14:39:44 +0000 2017',
      id: 903990830737768449,
      id_str: '903990830737768449',
      text: 'Update Perl 5.24 –&gt; 5.26 In Arch linux https://t.co/l3BugCIfW3',
      truncated: false,
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [],
        urls: [
          {
            url: 'https://t.co/l3BugCIfW3',
            expanded_url: 'http://dlvr.it/PkL627',
            display_url: 'dlvr.it/PkL627',
            indices: [42, 65],
          },
        ],
      },
      metadata: {
        iso_language_code: 'en',
        result_type: 'recent',
      },
      source: '<a href="https://dlvrit.com/" rel="nofollow">dlvr.it</a>',
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: null,
      in_reply_to_user_id_str: null,
      in_reply_to_screen_name: null,
      user: {
        id: 120655604,
        id_str: '120655604',
        name: 'Donato Roque',
        screen_name: 'findingdonato',
        location: 'Philippines',
        description:
          'music, history, movies, linux user, is:what keeps me up at nights',
        url: 'https://t.co/Z50ymKqROG',
        entities: {
          url: {
            urls: [
              {
                url: 'https://t.co/Z50ymKqROG',
                expanded_url: 'https://donatoroque.blogspot.com',
                display_url: 'donatoroque.blogspot.com',
                indices: [0, 23],
              },
            ],
          },
          description: {
            urls: [],
          },
        },
        protected: false,
        followers_count: 58,
        friends_count: 241,
        listed_count: 4,
        created_at: 'Sun Mar 07 04:04:37 +0000 2010',
        favourites_count: 337,
        utc_offset: 28800,
        time_zone: 'Hong Kong',
        geo_enabled: true,
        verified: false,
        statuses_count: 4172,
        lang: 'en',
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: true,
        profile_background_color: 'C0DEED',
        profile_background_image_url:
          'http://pbs.twimg.com/profile_background_images/688903218546360320/vAILLRED.png',
        profile_background_image_url_https:
          'https://pbs.twimg.com/profile_background_images/688903218546360320/vAILLRED.png',
        profile_background_tile: true,
        profile_image_url:
          'http://pbs.twimg.com/profile_images/3529336896/42f65d846353d9870a3688b621d2fdeb_normal.jpeg',
        profile_image_url_https:
          'https://pbs.twimg.com/profile_images/3529336896/42f65d846353d9870a3688b621d2fdeb_normal.jpeg',
        profile_banner_url:
          'https://pbs.twimg.com/profile_banners/120655604/1401494726',
        profile_link_color: '0084B4',
        profile_sidebar_border_color: '000000',
        profile_sidebar_fill_color: '000000',
        profile_text_color: '000000',
        profile_use_background_image: true,
        has_extended_profile: false,
        default_profile: false,
        default_profile_image: false,
        following: null,
        follow_request_sent: null,
        notifications: null,
        translator_type: 'none',
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 0,
      favorite_count: 0,
      favorited: false,
      retweeted: false,
      possibly_sensitive: false,
      lang: 'en',
    },
  ],
  search_metadata: {
    completed_in: 0.042,
    max_id: 904092837704237056,
    max_id_str: '904092837704237056',
    next_results:
      '?max_id=903990830737768448&q=arch%20linux&include_entities=1',
    query: 'arch+linux',
    refresh_url:
      '?since_id=904092837704237056&q=arch%20linux&include_entities=1',
    count: 15,
    since_id: 0,
    since_id_str: '0',
  },
};
